# Site
repository: ctudel/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chris Tudela
title: CS University Student
email: christudela@u.boisestate.edu

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  ctudel
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Chris and I'm a Computer Science student. Where I also have experience making various API and web applications. I have developed as part of project teams gaining leadership and communication skills.

  I am most skilled in: <mark>Java</mark> and <mark>HTML</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Stardew Valley
        quote: >
           Implements the back-end logic for Stardew Valley using a Heap Sort data structure algorithm, which will organize tasks and objectives based on a random generator and priority queue.
        description: | # this will include new lines to allow paragraphs
           Initiated as a learning endeavor in <mark>Data Structures</mark>, this project has evolved into a comprehensive implementation of the popular game, Stardew Valley. Throughout its development, I honed valuable skills in strategic planning and implementing of efficient data structures, contributing to the optimization and enhancement of the entire program.

      - layout: top-middle
        title: BTree
        quote: >
           Implementation of a BTree data structure for effectively handling and managing a large set of data with varying degree, allowing for efficient insertion and searching of data.
        description: |
           I developed this project as part of a team on, utilizing github as our primary version control. I have learned many skills required to work effectively on a team, efficiently developing a BTree while practicing agile development.
           
  - title: Relative Course Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Data Structures
        caption: Sept 2023 - Dec 2023
        quote: >
           Involves understanding the fundamental concepts of data structures — the building blocks that empower computer programs to handle, store, and manipulate information. 
        description: | # this will include new lines to allow paragraphs
            The course in Data Structures serves as a cornerstone in my academic journey, providing me with a solid foundation in organizing and managing data to develop efficient problem-solving in computer science.
    
      - layout: left
        title: Programming Languages
        caption: Present
        quote: >
           Teaches the principles and constructs of programming languages. Providing a deeper understanding of design, syntax, semantics, and more.
        description: |
           This course is valuable in gaining experience through hands-on exercises and projects to gain proficiency in writing clear, efficient code across different languages.
    
      - layout: left
        title: CS II
        caption: Jan 2023 - May 2023
        quote: >
           Explored the principles of object-oriented design, encompassing inheritance, polymorphism, recursion, and dynamic binding. 
        description: |
           In this course I learned numerous concepts about object-oriented design in java, as well as gain hands-on experience with junit testing.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Boise State University
        caption: 2021 - 2025
        sub_title: BSc Computer Science
        quote: >
          Situated in the bustling metropolis of Boise, Idaho, Boise State University is a shining example of academic excellence and innovation. Boise State, which is well-known for its dedication to encouraging creativity and critical thinking, provides students with a dynamic learning environment that equips them for success in a world that is always changing.
        description: | # this will include new lines to allow paragraphs
          During my time at BSU I learnt most of my key skills that I have taken through my college career such as teamwork and working to tight deadlines. I enjoy my time here and am currently learning a lot about healthy work life balance.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
